name: 'DAPI CI'
description: 'Validates and Registers DAPI or DATA APIs, made by Woven'
inputs:
  dapi-server-hostname:  # id of input
    description: 'Hostname of the DAPI server'
    required: True
  register-on-merge-to-mainline:  # id of input
    description: 'Whether DAPI files must be registered upon merge to mainline'
    type: boolean
    required: True
    default: False
  mainline-branch-name:  # id of input
    description: 'Name of the mainline branch'
    required: True
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: DAPI check
      id: dapi-check
      uses: actions/github-script@v6
      with:
        script: |
          const script = require('./.github/actions/dapi_ci/index.js');
          console.log(await script({context, core, exec, fetch, glob}));
