name: Woven DAPI CI
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: DAPI CI Action
      uses:  wovencollab/dapi-check@18c9e17a59d6fd29b0c1deb9c00bf8df11fa08d9
      with:
        dapi-server-hostname: "https://9xmk52u6t0.execute-api.us-east-1.amazonaws.com/dev/"
        mainline-branch-name: "main"
        register-on-merge-to-mainline: True
