name: Woven DAPI CI
on:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: DAPI CI Action
      uses:  ./.github/actions/dapi_ci
      with:
        dapi-server-hostname: "https://9xmk52u6t0.execute-api.us-east-1.amazonaws.com/dev/"
        mainline-branch-name: "main"
        register-on-merge-to-mainline: True
