name: Woven DAPI CI
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: DAPI CI Action
      uses:  wovencollab/dapi-check@a0f817d8a1d5659036e46700b45616b13d222afc
      with:
        dapi-server-hostname: "https://9xmk52u6t0.execute-api.us-east-1.amazonaws.com/dev/"
        mainline-branch-name: "main"
        register-on-merge-to-mainline: True
