name: Woven DAPI CI
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: DAPI CI Action
      uses:  wovencollab/dapi-check@a1e11c0f1a29ae87e7f47bd7c82a19b660ee0fe4
      with:
        dapi-server-hostname: "https://9xmk52u6t0.execute-api.us-east-1.amazonaws.com/dev/"
        mainline-branch-name: "main"
        register-on-merge-to-mainline: True
